sonar.projectKey=LmarDark_expert-bassoon_b756caf5-729e-4ad8-8b3b-b954a72a4829
sonar.coverage.exclusions=\
  database/migrations/**,\
  bootstrap/app.php,\
  routes/web.php,\
  app/Http/Requests/**,\
  tests/**,\
  resources/js/**
